### ISSUE TITLE
Merge tornado 4.5.0 autoreload changes

### ISSUE THREAD

**Issue by hellysmile** [and800/aioreloader#3]
http://www.tornadoweb.org/en/latest/releases/v4.5.0.html#tornado-autoreload

**Comment by and800** [comment]
It seems that the changes do not affect this package.
They removed a hook which, in order to gracefully close files, used to try to close the loop. Howewer, as they said in commit msg,
> it can't work with asyncio (which does not allow closing the IOLoop without stopping it and unwinding the stack first)

so I couldn't transfer this thing. Or, more likely, I even didn't try, because I didn't really care about graceful shutdown at all.
